name: back-end [API-Server] CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [16.13]
    defaults:
      run:
        working-directory: ./server/api

    steps:
      - uses: actions/checkout@v2
      - name: npm 모듈들을 캐싱합니다.
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: npm 으로 패키지 다운로드합니다.
        run: npm install

      - name: env 파일 생성
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          directory: ./server/api
          file_name: .env

      - name: CI 작업을 수행합니다.
        run: npm run ci

      - name: 테스트 코드를 실행합니다.
        run: npm test
